name: Deploy to AWS (Draft)

# Цей блок вказує, КОЛИ запускати автоматизацію (при кожному push у гілку main)
on:
  push:
    branches:
      - main

# Цей блок описує ЩО саме робити
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # GitHub виділить нам тимчасовий Linux-сервер для виконання задач
    
    steps:
      - name: Get the code
        uses: actions/checkout@v3
        
      - name: Test step (Echo)
        run: echo "Код успішно оновлено! Тут пізніше буде команда для відправки на AWS."
